# Generated by Django 3.0.8 on 2021-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
