# Generated by Django 3.0.8 on 2021-10-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20211004_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
