# Generated by Django 3.0.8 on 2021-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_field_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='duration',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
