# Generated by Django 3.2.8 on 2021-10-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20211005_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='field',
            name='total_marks',
        ),
    ]
