# Generated by Django 3.2.8 on 2021-10-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
