# Generated by Django 3.2.8 on 2021-10-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='field_name',
            new_name='code',
        ),
    ]
