# Generated by Django 3.0.8 on 2021-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210927_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('submitted', 'submitted')], default='submitted', max_length=20),
        ),
    ]
