# Generated by Django 3.0.8 on 2021-10-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('submitted', 'submitted')], default='pending', max_length=20),
        ),
    ]
