# Generated by Django 3.2.8 on 2021-10-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211005_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
