# Generated by Django 3.2.8 on 2021-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='susupicious',
            field=models.BooleanField(default=False),
        ),
    ]
