# Generated by Django 3.2.8 on 2021-10-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20211013_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
    ]
