# Generated by Django 3.2.8 on 2021-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_student_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
