# Generated by Django 3.2.8 on 2021-10-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_college_college_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
