# Generated by Django 3.2.8 on 2021-10-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.college'),
        ),
    ]
